In [1]:
import pandas as pd
import numpy as np

import sys
import math

sys.path.append('..')
import astroutils as astro

### Question 1.3

Converting degrees, arcminutes and arcseconds to radians and vice versa

In [12]:
astro.to_radians(sf = 6, degs=35, arcmins=44, arcsecs=36)

'0.623839'

In [13]:
astro.from_radians(sf=3,radians=0.623839)

('35', '44', '36')

### Question 1.4

Small angle approximation.

In [14]:
astro.to_radians(sf=4, arcsecs=30)

'0.0001454'

In [15]:
astro.to_sf(
    sf=4,
    res=math.sin(float(astro.to_radians(sf=4,arcsecs=30)))
)

'0.0001454'

### Question 1.5

Conversion of RA time coordinates to decimal degrees.

In [16]:
astro.ra_from_time_to_deg(sf=5, h=11, m=45, s=56.78)

'176.49'

### Example 1.4

Calculate the angular separation between `cyg_A_61` and `cyg_B_61` with positions:

`21h 06m 53.94s, +38deg 44arcmin 57.9arcsec`   
`21h 06m 55.26s, +38deg 44arcmin 31.4arcsec` 

respectively. Express your answer in arcseconds.


#### 1. Define locations

In [17]:
cyg_A_61_ra = np.array([21, 6, 53.94])
cyg_A_61_dec = np.array([38, 44, 57.9])
cyg_B_61_ra = np.array([21, 6, 55.26])
cyg_B_61_dec = np.array([38, 44, 31.4])

#### 2. Compute deltas.

In [18]:

delta_ra = cyg_A_61_ra - cyg_B_61_ra
delta_dec = cyg_A_61_dec - cyg_B_61_dec


In [19]:
delta_ra

array([ 0.  ,  0.  , -1.32])

In [20]:
delta_dec

array([ 0. ,  0. , 26.5])

#### 3. Convert RA delta to arcseconds.

In [21]:
delta_ra_arcseconds = delta_ra * 15

In [22]:
delta_ra_arcseconds

array([  0. ,   0. , -19.8])

#### 4. Compute RA distance

In [23]:
mean_dec = np.mean([
    cyg_A_61_dec,
    cyg_B_61_dec
], axis=0)

In [24]:
mean_dec_radians = float(astro.to_radians(
    sf=3, 
    degs=mean_dec[0], 
    arcmins=mean_dec[1], 
    arcsecs=mean_dec[2]
    )
)

In [25]:
mean_dec_radians

0.676

In [26]:
distance_ra_arcsecs = \
    delta_ra_arcseconds * math.cos(mean_dec_radians)

In [27]:
distance_ra_arcsecs

array([  0.        ,   0.        , -15.44561694])

#### 5. Compute theta

In [28]:
theta = math.sqrt(
    distance_ra_arcsecs[2]**2 + delta_dec[2]**2
)

In [29]:
astro.to_sf(sf=2, res=theta)

'31'

### Example 1.5

Converting angular separation to linear separation (or angular size to linear size).

Given the angular separation (or size) between two objects, we just need to know the distance to the objects to obtain the linear separation (or size).

This conversion relates the angular separation $\theta$ to the linear separation $D$ via the distance away $d$ using trigonometry:

$$\sin \theta = \frac{D}{d}$$

Taking the result of the previous example for the angular separation between _61 Cyg A_ and _61 Cyg B_, and the fact that they are 3.50 pc away from us, calculate their linear separation in AU.

First we can make use of the small angle approximation and use $\theta$ in radians as value for $\sin \theta$.

In [30]:
theta_radians = astro.to_radians(
    sf=6,
    arcsecs=theta
)

In [31]:

theta_radians

'0.000148706'

Then we can apply the formulate above.

In [32]:
linear_distance_pc = float(theta_radians) * 3.5

In [33]:
linear_distance_pc

0.000520471

In [34]:
astro.to_sf(
    sf=3, 
    res=astro.pc_to_au(linear_distance_pc))

'107'

### Question 1.7

Combining proper motion components.

The aparent movement of a star across the sky is called *proper motion*, and we can use the same approach used when computing angular and linear distances to determine movement.

Proper motion components refer to the proper motion in right ascension and declination, and can be defined as the changes in each component in time $\Delta t$.