In [1]:
import pandas as pd
import numpy as np

import sys
import math

sys.path.append('..')
import astroutils as astro

### Question 1.3

Converting degrees, arcminutes and arcseconds to radians and vice versa

In [2]:
astro.to_radians(sf = 6, degs=35, arcmins=44, arcsecs=36)

'0.623839'

In [3]:
astro.from_radians(sf=0,radians=0.623839)

35.74334179566176


('35', '44', '36')

### Question 1.4

Small angle approximation.

In [4]:
astro.to_radians(sf=4, arcsecs=30)

'0.0001'

In [5]:
astro.to_sf(
    sf=4,
    res=math.sin(float(astro.to_radians(sf=4,arcsecs=30)))
)

'0.0001'

### Question 1.5

Conversion of RA time coordinates to decimal degrees.

In [6]:
astro.ra_from_time_to_degs(sf=5, h=11, m=45, s=56.78)

'176.48658'

## Example 1.4

Calculate the angular separation between `cyg_A_61` and `cyg_B_61` with positions:

`21h 06m 53.94s, +38deg 44arcmin 57.9arcsec`   
`21h 06m 55.26s, +38deg 44arcmin 31.4arcsec` 

respectively. Express your answer in arcseconds.


#### 1. Define locations

In [7]:
cyg_A_61_ra = np.array([21, 6, 53.94])
cyg_A_61_dec = np.array([38, 44, 57.9])
cyg_B_61_ra = np.array([21, 6, 55.26])
cyg_B_61_dec = np.array([38, 44, 31.4])

#### 2. Compute deltas.

In [8]:

delta_ra = cyg_A_61_ra - cyg_B_61_ra
delta_dec = cyg_A_61_dec - cyg_B_61_dec


In [9]:
delta_ra

array([ 0.  ,  0.  , -1.32])

In [10]:
delta_dec

array([ 0. ,  0. , 26.5])

#### 3. Convert RA delta to arcseconds.

In [11]:
delta_ra_arcseconds = delta_ra * 15

In [12]:
delta_ra_arcseconds

array([  0. ,   0. , -19.8])

#### 4. Compute RA distance

In [13]:
mean_dec = np.mean([
    cyg_A_61_dec,
    cyg_B_61_dec
], axis=0)

In [14]:
mean_dec_radians = float(astro.to_radians(
    sf=3, 
    degs=mean_dec[0], 
    arcmins=mean_dec[1], 
    arcsecs=mean_dec[2]
    )
)

In [15]:
mean_dec_radians

0.676

In [16]:
distance_ra_arcsecs = \
    delta_ra_arcseconds * math.cos(mean_dec_radians)

In [17]:
distance_ra_arcsecs

array([  0.        ,   0.        , -15.44561694])

#### 5. Compute theta

In [18]:
theta = math.sqrt(
    distance_ra_arcsecs[2]**2 + delta_dec[2]**2
)

In [21]:
astro.to_sf(sf=2, res=theta)

'30.67'